### ISSUE TITLE
pip3 install target_folder/出现错误

### ISSUE THREAD

**Issue by SJingjia** [meiqua/patch_linemod#5]
您好，我在pip3 install linemodLevelup/时遇到了错误，是否因为python/pip/setuptools版本问题导致的？请问您是否有什么建议解决这一问题，error信息如下：

 ```
ERROR: Command errored out with exit status 1:
   command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-t4o_cl51/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-t4o_cl51/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-70hds906
       cwd: /tmp/pip-req-build-t4o_cl51/
  Complete output (104 lines):
  running bdist_wheel
  running build
  running build_ext
  -- The C compiler identification is GNU 5.4.0
  -- The CXX compiler identification is GNU 5.4.0
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found OpenCV: /usr/local (found suitable version "3.4.0", minimum required is "3")
  -- Found Open3D 0.9.0.0
  -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.5m.so (found suitable version "3.5.2", minimum required is "3")
  -- Found PythonInterp: /usr/bin/python (found version "3.5.2")
  -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.5m.so
  -- Found NumPy: /home/jiayir/.local/lib/python3.5/site-packages/numpy/core/include (found version "1.16.2")
  -- Performing Test HAS_FLTO
  -- Performing Test HAS_FLTO - Success
  -- LTO enabled
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /tmp/pip-req-build-t4o_cl51/build/temp.linux-x86_64-3.5
  Scanning dependencies of target cuda_renderer
  [  8%] Building CXX object cuda_renderer/CMakeFiles/cuda_renderer.dir/renderer.cpp.o
  [ 16%] Linking CXX static library libcuda_renderer.a
  [ 16%] Built target cuda_renderer
  Scanning dependencies of target renderer_test
  [ 25%] Building CXX object cuda_renderer/CMakeFiles/renderer_test.dir/test.cpp.o
  Scanning dependencies of target patch_linemod
  [ 33%] Building CXX object CMakeFiles/patch_linemod.dir/linemodLevelup.cpp.o
  [ 41%] Linking CXX executable renderer_test
  [ 41%] Built target renderer_test
  [ 50%] Building CXX object CMakeFiles/patch_linemod.dir/pose_renderer.cpp.o
  /tmp/pip-req-build-t4o_cl51/linemodLevelup.cpp: In member function ‘std::vector<int> linemodLevelup::Detector::addTemplate(const std::vector<cv::Mat>&, const string&, cv::Mat, std::vector<int>)’:
  /tmp/pip-req-build-t4o_cl51/linemodLevelup.cpp:2259:10: warning: variable ‘bb’ set but not used [-Wunused-but-set-variable]
       Rect bb = cropTemplates(tp, clusters);
            ^
  In file included from /tmp/pip-req-build-t4o_cl51/pose_renderer.cpp:1:0:
  /tmp/pip-req-build-t4o_cl51/pose_renderer.h: In constructor ‘PoseRenderer::PoseRenderer(std::string, cv::Mat, cv::Mat)’:
  /tmp/pip-req-build-t4o_cl51/pose_renderer.h:18:50: warning: ‘PoseRenderer::tris’ will be initialized after [-Wreorder]
       std::vector<cuda_renderer::Model::Triangle>& tris;
                                                    ^
  /tmp/pip-req-build-t4o_cl51/pose_renderer.h:14:26: warning:   ‘cuda_renderer::Model PoseRenderer::model’ [-Wreorder]
       cuda_renderer::Model model;
                            ^
  /tmp/pip-req-build-t4o_cl51/pose_renderer.cpp:3:1: warning:   when initialized here [-Wreorder]
   PoseRenderer::PoseRenderer(std::string model_path, cv::Mat depth, cv::Mat K):
   ^
  [ 58%] Linking CXX static library libpatch_linemod.a
  [ 58%] Built target patch_linemod
  Scanning dependencies of target patch_linemod_test
  [ 66%] Building CXX object CMakeFiles/patch_linemod_test.dir/test.cpp.o
  Scanning dependencies of target patch_linemod_pybind
  [ 75%] Building CXX object CMakeFiles/patch_linemod_pybind.dir/pybind11.cpp.o
  [ 83%] Linking CXX executable patch_linemod_test
  libpatch_linemod.a(linemodLevelup.cpp.o)：在函数‘linemodLevelup::Match::read(cv::FileNode const&)’中：
  linemodLevelup.cpp:(.text+0x4e5e)：对‘cv::read(cv::FileNode const&, std::string&, std::string const&)’未定义的引用
  collect2: error: ld returned 1 exit status
  CMakeFiles/patch_linemod_test.dir/build.make:146: recipe for target 'patch_linemod_test' failed
  make[2]: *** [patch_linemod_test] Error 1
  CMakeFiles/Makefile2:143: recipe for target 'CMakeFiles/patch_linemod_test.dir/all' failed
  make[1]: *** [CMakeFiles/patch_linemod_test.dir/all] Error 2
  make[1]: *** 正在等待未完成的任务....
  [ 91%] Building CXX object CMakeFiles/patch_linemod_pybind.dir/np2mat/ndarray_converter.cpp.o
  [100%] Linking CXX shared module ../lib.linux-x86_64-3.5/patch_linemod_pybind.cpython-35m-x86_64-linux-gnu.so
  [100%] Built target patch_linemod_pybind
  Makefile:83: recipe for target 'all' failed
  make: *** [all] Error 2
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-t4o_cl51/setup.py", line 69, in <module>
      zip_safe=False,
    File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/jiayir/.local/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.5/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-t4o_cl51/setup.py", line 33, in run
      self.build_extension(ext)
    File "/tmp/pip-req-build-t4o_cl51/setup.py", line 58, in build_extension
      subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
    File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for patch-linemod-pybind
  Running setup.py clean for patch-linemod-pybind
Failed to build patch-linemod-pybind
Installing collected packages: patch-linemod-pybind
    Running setup.py install for patch-linemod-pybind ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-t4o_cl51/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-t4o_cl51/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-4tm61fz0/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/jiayir/.local/include/python3.5m/patch-linemod-pybind
         cwd: /tmp/pip-req-build-t4o_cl51/
    Complete output (106 lines):
    running install
    running build
    running build_ext
    -- The C compiler identification is GNU 5.4.0
    -- The CXX compiler identification is GNU 5.4.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found OpenCV: /usr/local (found suitable version "3.4.0", minimum required is "3")
    -- Found Open3D 0.9.0.0
    -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.5m.so (found suitable version "3.5.2", minimum required is "3")
    -- Found PythonInterp: /usr/bin/python (found version "3.5.2")
    -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.5m.so
    -- Found NumPy: /home/jiayir/.local/lib/python3.5/site-packages/numpy/core/include (found version "1.16.2")
    -- Performing Test HAS_FLTO
    -- Performing Test HAS_FLTO - Success
    -- LTO enabled
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /tmp/pip-req-build-t4o_cl51/build/temp.linux-x86_64-3.5
    Scanning dependencies of target cuda_renderer
    [  8%] Building CXX object cuda_renderer/CMakeFiles/cuda_renderer.dir/renderer.cpp.o
    [ 16%] Linking CXX static library libcuda_renderer.a
    [ 16%] Built target cuda_renderer
    Scanning dependencies of target renderer_test
    [ 25%] Building CXX object cuda_renderer/CMakeFiles/renderer_test.dir/test.cpp.o
    Scanning dependencies of target patch_linemod
    [ 33%] Building CXX object CMakeFiles/patch_linemod.dir/linemodLevelup.cpp.o
    [ 41%] Linking CXX executable renderer_test
    [ 41%] Built target renderer_test
    [ 50%] Building CXX object CMakeFiles/patch_linemod.dir/pose_renderer.cpp.o
    /tmp/pip-req-build-t4o_cl51/linemodLevelup.cpp: In member function ‘std::vector<int> linemodLevelup::Detector::addTemplate(const std::vector<cv::Mat>&, const string&, cv::Mat, std::vector<int>)’:
    /tmp/pip-req-build-t4o_cl51/linemodLevelup.cpp:2259:10: warning: variable ‘bb’ set but not used [-Wunused-but-set-variable]
         Rect bb = cropTemplates(tp, clusters);
              ^
    In file included from /tmp/pip-req-build-t4o_cl51/pose_renderer.cpp:1:0:
    /tmp/pip-req-build-t4o_cl51/pose_renderer.h: In constructor ‘PoseRenderer::PoseRenderer(std::string, cv::Mat, cv::Mat)’:
    /tmp/pip-req-build-t4o_cl51/pose_renderer.h:18:50: warning: ‘PoseRenderer::tris’ will be initialized after [-Wreorder]
         std::vector<cuda_renderer::Model::Triangle>& tris;
                                                      ^
    /tmp/pip-req-build-t4o_cl51/pose_renderer.h:14:26: warning:   ‘cuda_renderer::Model PoseRenderer::model’ [-Wreorder]
         cuda_renderer::Model model;
                              ^
    /tmp/pip-req-build-t4o_cl51/pose_renderer.cpp:3:1: warning:   when initialized here [-Wreorder]
     PoseRenderer::PoseRenderer(std::string model_path, cv::Mat depth, cv::Mat K):
     ^
    [ 58%] Linking CXX static library libpatch_linemod.a
    [ 58%] Built target patch_linemod
    Scanning dependencies of target patch_linemod_test
    [ 66%] Building CXX object CMakeFiles/patch_linemod_test.dir/test.cpp.o
    Scanning dependencies of target patch_linemod_pybind
    [ 75%] Building CXX object CMakeFiles/patch_linemod_pybind.dir/pybind11.cpp.o
    [ 83%] Linking CXX executable patch_linemod_test
    libpatch_linemod.a(linemodLevelup.cpp.o)：在函数‘linemodLevelup::Match::read(cv::FileNode const&)’中：
    linemodLevelup.cpp:(.text+0x4e5e)：对‘cv::read(cv::FileNode const&, std::string&, std::string const&)’未定义的引用
    collect2: error: ld returned 1 exit status
    CMakeFiles/patch_linemod_test.dir/build.make:146: recipe for target 'patch_linemod_test' failed
    make[2]: *** [patch_linemod_test] Error 1
    CMakeFiles/Makefile2:143: recipe for target 'CMakeFiles/patch_linemod_test.dir/all' failed
    make[1]: *** [CMakeFiles/patch_linemod_test.dir/all] Error 2
    make[1]: *** 正在等待未完成的任务....
    [ 91%] Building CXX object CMakeFiles/patch_linemod_pybind.dir/np2mat/ndarray_converter.cpp.o
    [100%] Linking CXX shared module ../lib.linux-x86_64-3.5/patch_linemod_pybind.cpython-35m-x86_64-linux-gnu.so
    [100%] Built target patch_linemod_pybind
    Makefile:83: recipe for target 'all' failed
    make: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-t4o_cl51/setup.py", line 69, in <module>
        zip_safe=False,
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/jiayir/.local/lib/python3.5/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.5/distutils/command/install.py", line 583, in run
        self.run_command('build')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.5/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-t4o_cl51/setup.py", line 33, in run
        self.build_extension(ext)
      File "/tmp/pip-req-build-t4o_cl51/setup.py", line 58, in build_extension
        subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
      File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-t4o_cl51/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-t4o_cl51/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-4tm61fz0/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/jiayir/.local/include/python3.5m/patch-linemod-pybind Check the logs for full command output.`
```

**Comment by meiqua** [comment]
看起来是opencv没有配置好。c++单独能编译吗

**Comment by SJingjia** [comment]
> 看起来是opencv没有配置好。c++独立能编译吗

谢谢！确实是opencv没配置好，之前cv::FileNode读字符串会出错
